version: '3.8'

services:
  minecraft:
    build: .
    container_name: minecraft-craft-to-exile-2
    ports:
      - "25565:25565"
    environment:
      - EULA=TRUE
      - MEMORY=12G
      - TYPE=FORGE
      - VERSION=1.20.1
      - FORGE_VERSION=47.3.27
    volumes:
      - ./world:/minecraft/world
      - ./mods:/minecraft/mods
      - ./config:/minecraft/config
      - ./logs:/minecraft/logs
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 12G
        reservations:
          cpus: '4'
          memory: 12G
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mcstatus", "localhost:25565", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    tty: true
    stdin_open: true
    networks:
      - craft_to_exile2_net

networks:
  craft_to_exile2_net:
    driver: bridge 