version: '3.8'

services:
  minecraft:
    build: .
    container_name: minecraft-heroes
    ports:
      - "25565:25565"
    volumes:
      - ./world:/minecraft/world
      - ./logs:/minecraft/logs
      - ./backups:/minecraft/backups
      - ./server.properties:/minecraft/server.properties
      - ./mods:/minecraft/mods
      - ./config:/minecraft/config
      - ./datapacks:/minecraft/datapacks
    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      - minecraft_net

networks:
  minecraft_net:
    driver: bridge 
