["Client Settings"]
	#Append Block Interaction Range attribute line to relevant tooltips (e.g., tools)
	appendBlockInteractionRangeTooltip = false
	#Show the 'Hold [Shift] to expand...' hint when tooltips have hidden details (merged attributes or collapsed enchantments).
	showUsabilityHint = false
	#Collapse enchantment descriptions on gear by default, requiring Shift to be held to view them. Enchanted Books always show descriptions.
	collapseEnchantmentTooltipsOnGear = true

["Color Settings"]
	#Enable coloring for enchantment names in tooltips.
	colorEnchantmentNames = false
	#Hex color code (#RRGGBB) for regular enchantment names (if colorEnchantmentNames is true). Curses are always red.
	enchantmentNameColor = "#AAAAAA"
	#Hex color code (#RRGGBB) for enchantment description text.
	enchantmentDescriptionColor = "#808080"
	#Hex color code (#RRGGBB) for enchantments above their max level (excluding curses) if colorEnchantmentNames is true.
	superLeveledEnchantmentColor = "#FF55FF"
	#Define custom color rules for specific attributes in tooltips.
	#Format: "attribute_id:LOGIC[:#HEXCOLOR]"
	#  attribute_id: The ResourceLocation of the attribute (e.g., minecraft:generic.movement_speed).
	#  LOGIC: How to color the modifier value. Options: INVERTED, FIXED.
	#    INVERTED: Use the opposite of the attribute's default sentiment coloring (e.g., positive value = red).
	#    FIXED: Always use the specified hex color, regardless of value.
	#  :#HEXCOLOR: Required only if LOGIC is FIXED. The hex color code (e.g., #RRGGBB).
	#  (If no rule is specified for an attribute, vanilla default coloring is used).
	attributeColorOverrides = ["additionalentityattributes:generic.hitbox_height:FIXED:#808080", "additionalentityattributes:generic.hitbox_width:FIXED:#808080", "additionalentityattributes:generic.model_height:FIXED:#808080", "additionalentityattributes:generic.model_width:FIXED:#808080", "additionalentityattributes:generic.height:FIXED:#808080", "additionalentityattributes:generic.width:FIXED:#808080", "additionalentityattributes:generic.model_scale:FIXED:#808080", "additionalentityattributes:generic.mob_detection_range:INVERTED", "ranged_weapon:pull_time:INVERTED"]
